### ISSUE TITLE
WS shouldn't go through Cloudflare?

### ISSUE THREAD

**Issue by SaiQmon** [jzombie/docker-mqtt-mosquitto-cloudflare-tunnel#22]
Hi and thank you for a great tutorial.

I've been trying to publish my Mosquito Broker via Cloudflare for multiple days. I always end up situation and messages don't reach the broker. I've tried 1883, 8883 and now with websockets 9001. 
In every version I can reach the broker from LAN side, but never from Cloudflare. I've read few posts that Cloudflare shouldn't work with WS/WSS or MQTT standard ports at all?

Logs from MQTTX:
```
[2024-08-19 12:23:27] [INFO] Connection websocketlocal was edited, ID: a33c7f18-5e28-4f3f-ae0d-23b8fcee1e3b
[2024-08-19 12:23:27] [INFO] Assigned ID a33c7f18-5e28-4f3f-ae0d-23b8fcee1e3b to MQTTX client
[2024-08-19 12:23:27] [INFO] Client websocketlocal connected using MQTT/WS connection at ws://mqtt.XXXXXXXX.XXX:9001/mqtt
[2024-08-19 12:23:37] [INFO] The connection websocketlocal (clientID mqttx_45ffa45c) is offline. MQTT.js onOffline trigger
[2024-08-19 12:23:37] [INFO] Connection for websocketlocal closed, MQTT.js onClose trigger

```

Cloudflare service is up and running, I used it previously to connect with Node-Red externally. I removed it and replaced with MQTT purposes, and I can see it's HEATHLY on Cloudflare.

![image](https://github.com/user-attachments/assets/3ebfbd48-2e3d-48fc-b9cd-bfa064275439)

I've tried with "localhost:9001" - "192.168.1.11:9001" and "127.0.0.1:9001" - no difference.

I read that proxy-mode shouldn't be enabled. If it is, MQTT client tries to make connection for couple of seconds and fails. In this mode, DNS query returns correct values.

![image](https://github.com/user-attachments/assets/d61e4c64-0df4-4e8e-aeaf-11336d089cb3)

If I disable the proxy in Cloudflare so it's "DNS Only", MQTT client gives immediate answer of ENOTFOUND - as it cannot resolve the name. Meantime, all DNS queries fail - I don't know why?

![image](https://github.com/user-attachments/assets/d79eaefe-369c-463c-b667-71a8280ae70c)

Any ideas?

**Comment by jzombie** [comment]
Are you using the Docker Compose configuration in this repo or a different setup?

**Comment by jzombie** [comment]
@SaiQmon  I've been running WS through Cloudflare Tunnels.

I can't tell from the screenshots you provided, but that's not where I went to configure this.  I didn't have to manually add a `CNAME` from my recollection.

![Screenshot 2024-08-19 at 1 01 40 PM](https://github.com/user-attachments/assets/0b6ae2f1-bcc7-4717-9406-77d6e6db425f)

---

If you have configured Cloudflare Tunnels and are still trying to debug it:

If you're running a different configuration than I am, but are using Docker to connect to Cloudflare Tunnels, ensure that container has access to wherever your MQTT is running.  It might not be `localhost` or `127.0.0.1`.

**Comment by jzombie** [comment]
Instance should be accessible via port 443.

Updated the guide and added additional info here:  https://github.com/jzombie/docker-mqtt-mosquitto-cloudflare-tunnel/issues/25
