### ISSUE TITLE
Working via 4G LTE?

### ISSUE THREAD

**Issue by obitvn** [jzombie/docker-mqtt-mosquitto-cloudflare-tunnel#23]
Hello Sir, I am a Cloudflare user for many of my small websites. Previously, I have tried various ways to get the MQTT broker working through Cloudflare Tunnel without any success. From what I understand, Cloudflare does not support the MQTT or WebSocket protocols, so it cannot work. I searched on GitHub and came across your project, which surprised me. I have tried deploying it exactly as you instructed, but I cannot connect to the MQTT via the domain. Have you actually tested and experimented with it?

**Comment by jzombie** [comment]
Yes, it works for me; that's why I built this repo to solve a use case that I had.

I haven't tested it with 4G LTE, but I use it from Nicaragua, which is connected to a server in the U.S.

**Comment by jzombie** [comment]
@obitvn, this forum post provides additional context: https://community.cloudflare.com/t/mqtt-trough-cloudflare-tunnel/503599

**Comment by jzombie** [comment]
Instance should be accessible via port 443.

Updated the guide and added additional info here:  https://github.com/jzombie/docker-mqtt-mosquitto-cloudflare-tunnel/issues/25
